// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivwivuvukhhuomoklhlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2d2l2dXZ1a2hodW9tb2tsaGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTM2MTAsImV4cCI6MjA2Mjg4OTYxMH0.-mw6eUv4Wwh0eJGyP7ngIRqVPJZ1oxrKz7ttQzkP_og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);